#Example configuration options that can be placed in your main SiriProxy config.yml

##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################
    
    - name: 'Plex'
      git: 'git://github.com/whoismezero/SiriProxy-Plex.git'
      plex_host: '10.0.1.75' #Internal IP address of your Plex Media Server.
      plex_port: '32400' #Most likely you won't have to change this, it runs on port 32400 by default.
      plex_tv_index: '2' #This is the path to your TV index within PMS, set to 'auto' to autodetect TV sections.
      plex_movie_index: '1' #This is the path to your Movie index within PMS, set to 'auto' for autodetect.
